version: '3.8'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
     # MYSQL_PASSWORD: ${DB_PASSWORD}
     # MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ~/database:/var/lib/mysql
    networks:
      - db-network

  backend:
    image: rejdaqati/travel-mate-backend:${TAG}
    restart: unless-stopped
    ports:
      - "8000:80"   
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY} 
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network
      - db-network

  frontend:
    image: rejdaqati/travel-mate-frontend:${TAG}
    #ports:
    # - "3000:80"
    networks:
      - app-network
    environment:
      VITE_API_URL: "/api"

  certbot:
   image: certbot/certbot
   volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - db-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  database:
networks:
  app-network:
    driver: bridge
  db-network:
