version: '3.8'

services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
     # MYSQL_PASSWORD: ${DB_PASSWORD}
     # MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ~/database:/var/lib/mysql
    networks:
      - db-network

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       # MYSQL_PASSWORD: ${DB_PASSWORD}
       # MYSQL_USER: ${DB_USERNAME}
       # MYSQL_PORT: ${DB_PORT}
#    command: bash -c "sleep 10 && php artisan migrate --seed && apache2-foreground"
    depends_on:
      - db
    networks:
      - app-network
      - db-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  certbot:
   image: certbot/certbot
   volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - db-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/travelmate.ovh/fullchain.pem:/etc/ssl/certs/travelmate.crt
      - /etc/letsencrypt/live/travelmate.ovh/privkey.pem:/etc/ssl/private/travelmate.key
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  database:
networks:
  app-network:
    driver: bridge
  db-network:
